{
 "title": "coronavirus (COVID-19)  Spread Map Brazil",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   {
    "name": "type",
    "query": "cases_cum,cases_cum_norm,deaths_cum,deaths_cum_norm"
   }
  ]
 },
 "panels": [
  {
   "title": "Spread Map Brazil showing [[type]]",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"Acre\"\nFROM brazil_states_diff\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "content": "# Spreadmap Brazil states\n* cases_cum: cumulative confirmed cases\n* cases_cum_norm: cumulative confirmed cases normalized per 100.000 inhabitants\n* deaths_cum: cumulative deaths\n* deaths_cum_norm: cumulative deaths normalized per 100.000 inhabitants\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"Albania\"\nFROM \"world_timeseries_EU_diff\"\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19)  Spread Map Netherlands",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   {
    "name": "type",
    "query": "Totaal_Absoluut,Totaal_inc100000"
   }
  ]
 },
 "panels": [
  {
   "title": "Spread Map Netherlands",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"Algeria\"\nFROM \"world_timeseries_AF_diff\"\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Age Statistics RIVM Latest",
 "time": { "from": "2020-03-19T09:54:54.318Z", "to": "2020-03-19T21:54:54.318Z" },
 "panels": [
  { "title": "Current numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total IC Cases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", SUM(\"newIntake\") as \"IC admissions\" from \"corona-IC\""
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", SUM(\"Overleden\") from netherlands_rivm_current_age"
    }
   ]
  },
  { "title": "IC Admissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "IC admissions percentage per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"0\" as age, \"1\" as values from \"corona-IC-age\""
    }
   ]
  },
  {
   "title": "IC admissions percentage per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"0\" as age, \"1\" as values from \"corona-IC-age\""
    }
   ]
  },
  {
   "title": "IC admissions percentage per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"0\" as age, \"1\" as values from \"corona-IC-age\""
    }
   ]
  },
  { "title": "Deaths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Deaths per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Overleden\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Deaths per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Overleden\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Deaths per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Overleden\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 52 },
   "content": "\nsource: [China CDC](http://weekly.chinacdc.cn/en/article/id/e53946e2-c6c4-41e9-9a9b-fea8db1a8f51)\n\n\n"
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Age Statistics RIVM Latest (deprecated)",
 "time": { "from": "2020-03-19T09:54:54.318Z", "to": "2020-03-19T21:54:54.318Z" },
 "panels": [
  { "title": "Current numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Confirmed Cases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", SUM(\"Totaal\") from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", SUM(\"Overleden\") from netherlands_rivm_current_age"
    }
   ]
  },
  { "title": "Confirmed Cases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Confirmed cases per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Totaal\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Confirmed cases per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Totaal\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Confirmed cases per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Totaal\" from netherlands_rivm_current_age"
    }
   ]
  },
  { "title": "Hospital Admissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Hospital admissions per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Ziekenhuisopname\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Hospital admissions per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Ziekenhuisopname\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Hospital admissions per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Ziekenhuisopname\" from netherlands_rivm_current_age"
    }
   ]
  },
  { "title": "IC Admissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "IC admissions per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"0\" as age, \"1\" as values from \"corona-IC-age\""
    }
   ]
  },
  {
   "title": "IC admissions per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"0\" as age, \"1\" as values from \"corona-IC-age\""
    }
   ]
  },
  {
   "title": "IC admissions per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"0\" as age, \"1\" as values from \"corona-IC-age\""
    }
   ]
  },
  { "title": "Deaths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Deaths per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Overleden\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Deaths per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Overleden\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "title": "Deaths per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", \"Leeftijdsgroep\", \"Overleden\" from netherlands_rivm_current_age"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 98 },
   "content": "\nsource: [China CDC](http://weekly.chinacdc.cn/en/article/id/e53946e2-c6c4-41e9-9a9b-fea8db1a8f51)\n\n\n"
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Brazil Overview",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Confirmed cases in Brazil",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \"time\", \"cases_cum\" from brazil_whole WHERE $__timeFilter(\"time\")"
    },
    {
     "rawSql": "select \"time\", \"cases_new\" from brazil_whole WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Deaths in Brazil",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \"time\", \"deaths_cum\" from brazil_whole WHERE $__timeFilter(\"time\")"
    },
    {
     "rawSql": "select \"time\", \"deaths_new\" from brazil_whole WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Distribution of confirmed cases over States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select \"time\", \"state\", \"cases_cum\" from brazil_states WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Distribution of deaths over States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select \"time\", \"state\", \"deaths_cum\" from brazil_states WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Distribution of confirmed new cases over States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select \"time\", \"state\", \"cases_new\" from brazil_states WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Distribution of new deaths over States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select \"time\", \"state\", \"deaths_new\" from brazil_states WHERE $__timeFilter(\"time\")"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Brazil per state",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "select name from static_brazil_states"
   }
  ]
 },
 "panels": [
  {
   "title": "Confirmed cases in [[state]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \"time\", \"cases_cum\" from brazil_states where state='[[state]]' AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Deaths in [[state]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \"time\", \"deaths_cum\" from brazil_states where state='[[state]]' AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Daily Confirmed cases in [[state]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \"time\", \"cases_new\" from brazil_states where state='[[state]]' AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Daily Deaths in [[state]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \"time\", \"deaths_new\" from brazil_states where state='[[state]]' AND $__timeFilter(\"time\")"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Netherlands Cities (Multiple)",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  {
   "title": "Latest known numbers for all cities (for a two week period per RIVM)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \"Gemeente\", \"Totaal_inc100000\" as \"New cases per 100.000\", \"Zkh_inc100000\" as \"Hospital admissions per 100.000\", \"Overleden_inc100000\" as \"Deaths per 100.000\" from netherlands_cities_2weeks where time > current_date - interval '14 days'"
    }
   ]
  },
  {
   "title": "Latest known numbers for all cities (for a two week period per RIVM)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select \"Gemeente\", \"Totaal_Absoluut\" as \"New cases\", \"Zkh_Absoluut\" as \"Hospital admissions\", \"Overleden_Absoluut\" as \"Deaths\" from netherlands_cities_2weeks where time > current_date - interval '14 days'"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 18 },
   "options": {
    "content": "Make selection of cities by holding CTRL or SHIFT and left clicking on cities on the right  \n(grafana only supports this on desktop)"
   },
   "content": "Make selection of cities by holding CTRL or SHIFT and left clicking on cities on the right (for now only on desktop)"
  },
  {
   "title": "New Confirmed cases per 100.000 per city per two weeks",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Gemeente\", \"Totaal_inc100000\" from netherlands_cities_2weeks"
    }
   ]
  },
  {
   "title": "New hospital admissions per 100.000 per city per two weeks",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Gemeente\", \"Zkh_inc100000\" from netherlands_cities_2weeks"
    }
   ]
  },
  {
   "title": "New deaths per 100.000 per city per two weeks",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Gemeente\", \"Overleden_inc100000\" from netherlands_cities_2weeks"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Netherlands Cities (Single) 2 weeks average",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "query": "select \"Gemeente\" from netherlands_cities_2weeks;"
   }
  ]
 },
 "panels": [
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "At first this showed calculated values, but for simplicity this now follows the RIVM reporting.\nThis means two week intervals of known cases."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"Algeria\"\nFROM \"world_timeseries_AF_diff\"\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "New cases per two weeks in [[city]]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Totaal_Absoluut\" from netherlands_cities_2weeks where \"Gemeente\" = '[[city]]'"
    }
   ]
  },
  {
   "title": "New hospital admissions per two weeks in [[city]]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Zkh_Absoluut\" from netherlands_cities_2weeks where \"Gemeente\" = '[[city]]'"
    }
   ]
  },
  {
   "title": "Deaths per two weeks in [[city]]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Overleden_Absoluut\" from netherlands_cities_2weeks where \"Gemeente\" = '[[city]]'"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Netherlands Cities (Single) per day",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "query": "select \"Gemeente\" from netherlands_cities_2weeks;"
   }
  ]
 },
 "panels": [
  {
   "title": "Cases in [[city]]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, sum(\"Totaal_Absoluut\") OVER (ORDER BY time) as \"New cases\" from netherlands_cities where \"Municipality_name\" = '[[city]]'"
    },
    {
     "rawSql": "select time, \"Totaal_Absoluut\" as \"New cases per day\" from netherlands_cities where \"Municipality_name\" = '[[city]]'"
    }
   ]
  },
  {
   "title": "Hospital admissions in [[city]]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, sum(\"Zkh_Absoluut\") OVER (ORDER BY time) as \"Hospital admissions\" from netherlands_cities where \"Municipality_name\" = '[[city]]'"
    },
    {
     "rawSql": "select time, \"Zkh_Absoluut\" as \"Hospital admissions per day\" from netherlands_cities where \"Municipality_name\" = '[[city]]'"
    }
   ]
  },
  {
   "title": "Deaths in [[city]]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, sum(\"Overleden_Absoluut\") OVER (ORDER BY time) as \"Deaths\" from netherlands_cities where \"Municipality_name\" = '[[city]]'"
    },
    {
     "rawSql": "select time, \"Overleden_Absoluut\" as \"Deaths per day\" from netherlands_cities where \"Municipality_name\" = '[[city]]'"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) per continent",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "continent",
    "label": "Continent to display (ISO code)",
    "query": "EU,NA,SA,AS,AF,OC"
   }
  ]
 },
 "panels": [
  {
   "title": "Confirmed Cases in [[continent]]",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from \"world_timeseries_[[continent]]\" where type='confirmed'"
    }
   ]
  },
  {
   "title": "Deaths in [[continent]]",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from \"world_timeseries_[[continent]]\" where type='deaths'"
    }
   ]
  },
  {
   "title": "New confirmed cases in [[continent]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from \"world_timeseries_[[continent]]_diff\" where type='confirmed'"
    }
   ]
  },
  {
   "title": "Deaths per day in [[continent]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from \"world_timeseries_[[continent]]_diff\" where type='deaths'"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) per country",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country to view data of",
    "query": "select column_name from information_schema.columns where table_name like '%timeseries%' and data_type='bigint';"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Cases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select time,\"[[country]]\" from \"world_timeseries_AF\" NATURAL JOIN \"world_timeseries_AS\" NATURAL JOIN \"world_timeseries_EU\" NATURAL JOIN \"world_timeseries_NA\" NATURAL JOIN \"world_timeseries_OC\" NATURAL JOIN \"world_timeseries_SA\" where type='confirmed'  ORDER BY time DESC limit 1"
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "select time,\"[[country]]\" from \"world_timeseries_AF\" NATURAL JOIN \"world_timeseries_AS\" NATURAL JOIN \"world_timeseries_EU\" NATURAL JOIN \"world_timeseries_NA\" NATURAL JOIN \"world_timeseries_OC\" NATURAL JOIN \"world_timeseries_SA\" where type='deaths'  ORDER BY time DESC limit 1"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Confirmed cases in [[country]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,\"[[country]]\" from \"world_timeseries_AF\" NATURAL JOIN \"world_timeseries_AS\" NATURAL JOIN \"world_timeseries_EU\" NATURAL JOIN \"world_timeseries_NA\" NATURAL JOIN \"world_timeseries_OC\" NATURAL JOIN \"world_timeseries_SA\" where type='confirmed'"
    }
   ]
  },
  {
   "title": "Deaths in [[country]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,\"[[country]]\" from \"world_timeseries_AF\" NATURAL JOIN \"world_timeseries_AS\" NATURAL JOIN \"world_timeseries_EU\" NATURAL JOIN \"world_timeseries_NA\" NATURAL JOIN \"world_timeseries_OC\" NATURAL JOIN \"world_timeseries_SA\" where type='deaths'"
    }
   ]
  },
  {
   "title": "New confirmed cases in [[country]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,\"[[country]]\" from \"world_timeseries_AF_diff\" NATURAL JOIN \"world_timeseries_AS_diff\" NATURAL JOIN \"world_timeseries_EU_diff\" NATURAL JOIN \"world_timeseries_NA_diff\" NATURAL JOIN \"world_timeseries_OC_diff\" NATURAL JOIN \"world_timeseries_SA_diff\" where type='confirmed'"
    }
   ]
  },
  {
   "title": "Deaths per day in [[country]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,\"[[country]]\" from \"world_timeseries_AF_diff\" NATURAL JOIN \"world_timeseries_AS_diff\" NATURAL JOIN \"world_timeseries_EU_diff\" NATURAL JOIN \"world_timeseries_NA_diff\" NATURAL JOIN \"world_timeseries_OC_diff\" NATURAL JOIN \"world_timeseries_SA_diff\" where type='deaths'"
    }
   ]
  },
  {
   "title": "Confirmed cases in [[country]] (log plot)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,\"[[country]]\" from \"world_timeseries_AF\" NATURAL JOIN \"world_timeseries_AS\" NATURAL JOIN \"world_timeseries_EU\" NATURAL JOIN \"world_timeseries_NA\" NATURAL JOIN \"world_timeseries_OC\" NATURAL JOIN \"world_timeseries_SA\" where type='confirmed'"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) State in Netherlands",
 "time": { "from": "2020-02-26T19:06:01.000Z", "to": "now" },
 "panels": [
  {
   "title": "Hospital admissions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Ziekenhuisopname_add\" as \"Total hospital admissions\"  from netherlands_rivm_hospitals WHERE $__timeFilter(\"time\")"
    },
    {
     "rawSql": "select time, \"Ziekenhuisopname\" as \"Hospital admissions\"  from netherlands_rivm_hospitals WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "IC admissions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select date as time, \"intakeCumulative\" as \"Total IC admissions\" from \"corona-IC\" WHERE $__timeFilter(\"date\")"
    },
    {
     "rawSql": "select date as time, \"newIntake\" as \"IC admissions\" from \"corona-IC\" WHERE $__timeFilter(\"date\")"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"deaths_cum\" as \"Total Deaths\" from \"netherlands_rivm_deaths\" WHERE $__timeFilter(\"time\")"
    },
    {
     "rawSql": "select time, \"deaths\" as \"Deaths\" from \"netherlands_rivm_deaths\" WHERE $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Actual IC situation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select date as time, \"intakeCount\" as \"active in IC\" from \"corona-IC\" WHERE $__timeFilter(\"date\")"
    },
    {
     "rawSql": "select date as time, \"newIntake\" as \"New Admissions\" from \"corona-IC\" WHERE $__timeFilter(\"date\")"
    }
   ]
  },
  {
   "title": "Confirmed Cases",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, \"Cases_add\" as \"Total cases\", \"Cases\" as \"New Cases\"  from \"netherlands_rivm_hospitals\" WHERE $__timeFilter(\"time\")"
    }
   ]
  }
 ]
}
{
 "title": "coronavirus (COVID-19) Statistics China CDC",
 "time": { "from": "2020-03-19T09:54:54.318Z", "to": "2020-03-19T21:54:54.318Z" },
 "panels": [
  {
   "title": "Total Confirmed Cases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", confirmed from china_stats where \"type\"='Overall'"
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", deaths from china_stats where \"type\"='Overall'"
    }
   ]
  },
  { "title": "Confirmed Cases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Confirmed cases per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", type, confirmed from china_stats where \"type\"!='Overall' and \"type\"!='Male' and \"type\"!='Female'"
    }
   ]
  },
  {
   "title": "Confirmed cases per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", type, confirmed from china_stats where \"type\"!='Overall' and \"type\"!='Male' and \"type\"!='Female'"
    }
   ]
  },
  {
   "title": "Confirmed cases per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", type, confirmed from china_stats where \"type\"!='Overall' and \"type\"!='Male' and \"type\"!='Female'"
    }
   ]
  },
  { "title": "Deaths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Deaths per age group",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", type, deaths from china_stats where \"type\"!='Overall' and \"type\"!='Male' and \"type\"!='Female'"
    }
   ]
  },
  {
   "title": "Deaths per age group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", type, deaths from china_stats where \"type\"!='Overall' and \"type\"!='Male' and \"type\"!='Female'"
    }
   ]
  },
  {
   "title": "Deaths per age group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select NOW() AS \"time\", type, deaths from china_stats where \"type\"!='Overall' and \"type\"!='Male' and \"type\"!='Female'"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 51 },
   "content": "\nsource: [China CDC](http://weekly.chinacdc.cn/en/article/id/e53946e2-c6c4-41e9-9a9b-fea8db1a8f51)\n\n\n"
  }
 ]
}
{
 "title": "coronavirus (COVID-19) World statistics normalized",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Deaths per 100.000 population",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select * from world_timeseries_per_pop where \"type\"='deaths'"
    }
   ]
  }
 ]
}
{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Welcome to boerman.dev Grafana dashboard server\n\nHere you can find various visualizations that I find personally interesting. If you have any questions feel free to shoot me an email at frank@fboerman.nl \n\nFor more information about me and some of my projects you can visit my blog at [https://boerman.dev/](https://boerman.dev/)\n\n\n\n"
   },
   "content": "\n# Welcome to boerman.dev Grafana dashboard server\n\nHere you can find various visualizations that I find personally interesting. If you have any questions feel free to shoot me an email at frank@fboerman.nl \n\nFor more information about me and some of my projects you can visit my blog at [https://boerman.dev/](https://boerman.dev/)\n\n\n\n"
  },
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 4 },
   "options": {
    "content": "# Dashboard overview\n\n## Netherlands:\n* [Current state, overal cases & deaths, hospital & IC situation](https://data.boerman.dev/d/wYiRAmjZz/coronavirus-covid-19-state-in-netherlands?orgId=1)\n* 2 week average per city [single](https://data.boerman.dev/d/vCk8JoXZk/coronavirus-covid-19-netherlands-cities-single?orgId=1), [all together](https://data.boerman.dev/d/-QdhSKuZz/coronavirus-covid-19-netherlands-cities-multiple?orgId=1)\n* daily per city [single](https://data.boerman.dev/d/lJkvwyKGk/coronavirus-covid-19-netherlands-cities-single-per-day?orgId=1)\n* [spread map per municipal](https://data.boerman.dev/d/xNbilX9Zz/coronavirus-covid-19-spread-map-netherlands?orgId=1)\n* [age statistics](https://data.boerman.dev/d/QwCZX9uFv/coronavirus-covid-19-age-statistics-rivm-latest?orgId=1)\n* [hotspot alarm](https://data.boerman.dev/d/iSZYMUKMz/hotspot-alarm?orgId=1)\n \n## World:\n* [cases and deaths per country](https://data.boerman.dev/d/_WmAJNXZz/coronavirus-covid-19-per-country?orgId=1)\n* [cases and deaths per continent](https://data.boerman.dev/d/wWiBrSuWz/coronavirus-covid-19-per-continent?orgId=1)\n\n## Brazil:\n* [per state](https://data.boerman.dev/d/i886RdrZz/coronavirus-covid-19-brazil-per-state?orgId=1)\n* [overview of all states and Country combined](https://data.boerman.dev/d/DkR44xiGk/coronavirus-covid-19-brazil-overview?orgId=1)\n* [spread map](https://data.boerman.dev/d/fqa7kRCWz/coronavirus-covid-19-spread-map-brazil?orgId=1)\n\n"
   },
   "content": "# Dashboard overview\n\n## Netherlands:\n* [Current state, overal cases & deaths, hospital & IC situation](https://data.boerman.dev/d/wYiRAmjZz/coronavirus-covid-19-state-in-netherlands?orgId=1)\n* per city [single](https://data.boerman.dev/d/vCk8JoXZk/coronavirus-covid-19-netherlands-cities-single?orgId=1), [all together](https://data.boerman.dev/d/-QdhSKuZz/coronavirus-covid-19-netherlands-cities-multiple?orgId=1)\n* [hospital admissions](https://data.boerman.dev/d/4Puzj19Wz/coronavirus-covid-19-hospitals-statistics-rivm-latest?orgId=1)\n* [spread map per municipal](https://data.boerman.dev/d/xNbilX9Zz/coronavirus-covid-19-spread-map-netherlands?orgId=1)\n* [age statistics](https://data.boerman.dev/d/QwCZX9uFv/coronavirus-covid-19-age-statistics-rivm-latest?orgId=1)\n \n## World:\n* [cases and deaths per country](https://data.boerman.dev/d/_WmAJNXZz/coronavirus-covid-19-per-country?orgId=1)\n* [cases and deaths per continent](https://data.boerman.dev/d/wWiBrSuWz/coronavirus-covid-19-per-continent?orgId=1)\n\n## Brazil:\n* [per state](https://data.boerman.dev/d/i886RdrZz/coronavirus-covid-19-brazil-per-state?orgId=1)\n* [overview of all states and Country combined](https://data.boerman.dev/d/DkR44xiGk/coronavirus-covid-19-brazil-overview?orgId=1)\n* [spread map](https://data.boerman.dev/d/fqa7kRCWz/coronavirus-covid-19-spread-map-brazil?orgId=1)\n\n"
  },
  { "title": "Available Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 20, "x": 0, "y": 17 } }
 ]
}
{
 "title": "Hotspot Alarm",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "City",
    "query": "select \"Gemeente\" from netherlands_cities_2weeks;"
   }
  ]
 },
 "panels": [
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Guidelines\n\nHotspots are defined as having more then 30 new cases per 100.000 or\nmore then 1 hospital admission per 100.000 accumulated over the last two weeks.\n\nBased on the two weeks aggregated data published by RIVM"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"Algeria\"\nFROM \"world_timeseries_AF_diff\"\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select  time, \"Totaal_inc100000\" as \"Cases per 100.000 (limit 30)\" from netherlands_cities_2weeks where \"Gemeente\" = '[[City]]';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select  time, \"Zkh_inc100000\" as \"Hospital admissions per 100.000 (limit 1)\" from netherlands_cities_2weeks where \"Gemeente\" = '[[City]]';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select  time, \"Totaal_inc100000\" as \"Cases per 100.000 in Arnhem\" from netherlands_cities_2weeks where \"Gemeente\" = 'Arnhem';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select  time, \"Zkh_inc100000\" as \"Hospital admissions per 100.000 in Arnhem\" from netherlands_cities_2weeks where \"Gemeente\" = 'Arnhem';"
    }
   ]
  }
 ]
}